[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx medusa db:migrate && npx medusa start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "always"

[build.setup]
nixPkgs = ["nodejs_20"]
